# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pantauinMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pantauinMessage.proto',
  package='',
  serialized_pb=_b('\n\x15pantauinMessage.proto\"?\n\x08Pantauin\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x13\n\x0bsensorValue\x18\x02 \x02(\x02\x12\x12\n\nnodeStatus\x18\x03 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PANTAUIN = _descriptor.Descriptor(
  name='Pantauin',
  full_name='Pantauin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Pantauin.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorValue', full_name='Pantauin.sensorValue', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeStatus', full_name='Pantauin.nodeStatus', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Pantauin'] = _PANTAUIN

Pantauin = _reflection.GeneratedProtocolMessageType('Pantauin', (_message.Message,), dict(
  DESCRIPTOR = _PANTAUIN,
  __module__ = 'pantauinMessage_pb2'
  # @@protoc_insertion_point(class_scope:Pantauin)
  ))
_sym_db.RegisterMessage(Pantauin)


# @@protoc_insertion_point(module_scope)
