/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Tue Dec 27 10:17:51 2016. */

#include "pantauinMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Pantauin_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Pantauin, id, id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Pantauin, sensorValue, id, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, Pantauin, nodeStatus, sensorValue, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
